### Listar itens
GET https://localhost:5001/api/item/listar

### Buscar item/produto
GET https://localhost:5001/api/item/buscar/2345

### Cadastrar um item/produto
POST https://localhost:5001/api/item/cadastrar
Content-Type: application/json

{
    "Produto" : "teste2",
    "Codigo" : "78912",
    "Preco" : 1870,
    "Marca" : "Motorola",
    "Modelo" : "Gplay",    
    "Quantidade" : "26"
}

### Alterar um item/produto
PATCH https://localhost:5001/api/item/alterar
Content-Type: application/json

{
    "ItensId" : "3",
    "Produto" : "Mouse",
    "Codigo" : "2345",
    "Preco" : 1000,
    "Marca" : "Razer",
    "Modelo" : "Teste",    
    "Quantidade" : "5"
}

### Deletar um item/produto/
DELETE https://localhost:5001/api/item/deletar/1

